<a href="https://colab.research.google.com/github/ayeshnayana/My-machine-learning/blob/master/tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

Since we are using the google colab we have to pre define the following. If you are using other programs like jupyter or pycharm this line is not required

%tensorflow_version 2.x


In [2]:
%tensorflow_version 2.x

In [3]:
import tensorflow as tf
print(tf.version) # to make sure we are using the correct version of tensorflow

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


Tensor is a generalization of a vector for n dimensions.
In tensorflow each tensor represents a partially defined computation that will eventually produce a value.

For example, tensor1= tensor2+tensor3 does not executed immidiately. We just use a representation or the relationship between tensor1, tensor2 and tensor3.
These tensor representations are kmnown as a graph. When executing a section or large set of these representions we call it a session.

Finally, when we execute whole session each of these tensor relationships will be evaluated and produce a value.

Each tensor has two main attributes 

<b>data types</b>: float 32, int32, strings and others

<b>shape</b>: Represents the dimension of data

# Creating a tensor

Below is an example of a tensor

In [4]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
float_num = tf.Variable(3.567, tf.float64)

# Rank/Degree of tensors

Both rank and degree of a tensor is mutable(exchangeble). Simply, these terms tells us how many dimensions does a given tensor have.

For example, the tensors that are defined in the previouse section are scalars. So they have zero dimensions. We call them scalars because they only contain one information such as "string, int" or "float".

But if we aggragate scalars and create an array then that would be a tensor of rank one. This is also known as a vector.

Now we can ggragate more vectors toghether. 

For example, if we aggragate two vectors we are making a matrix and this is a tensor of rank2. Like wise we can add more dimensionality. For example, 3d matrices represents a tensor of rank 3

In [11]:
rank1_tensor = tf.Variable(["tests", "ok", "tim"], tf.string)
rank2_tensor = tf.Variable([["tests", "ok", "tim"], ["store", "food", "eat"]], tf.string)

To detemine the rank of a tensor: tf.rank(<tensor_name>)

In [7]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Shape of a tensor

To get the shape of a tensor we use shape attribute

In [12]:
rank2_tensor.shape

TensorShape([2, 3])

# Changing the shape of a tensor

In [16]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a tensor of shape [1,2,3] full of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape the tensor to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3,-1]) # when -1 is used the tf will automatically determine what should be the numebr of columns based on the number of elements 

# in the thiord example we define the tensor to have 3 rows but the tensor2 has only 6 elements. So tf automatically detemnine that the number of rows shouldbe 2

In [14]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [25]:
t = tf.ones([5,5,4,4])
t =tf.reshape(t, [100,-1])
print(t)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]

# Types of tensors

-Variable

-Constant

-Placeholder

-SpaceTensor

except the Variable all the other types of tensors are immutable(cannot be change during the execution)


# Evaluating tensors

To evaluate the tensor relation we use a session. The tensor representaions are stored in graphs and in a session we evaluate these graphs.

To initaite a session we use the following defould block of code

In [ ]:
with tf.Session() as sess: # Create a session using default graph
  tensor.eval() # here the tensor is your variable (final output)



Tensorflow will automatically determine what graph it needs to evaluate to obtain the valueof the tensor